sys:
  auth:
    tokenHeaderName: auth-token
server:
  port: ${SERVER_PORT:9002}
spring:
  application:
    name: system
  web:
    allowedOriginPatterns:
      - http://localhost:**
      - http://10.96.**
    resources:
      static-locations: file:resources/uploads/
  mvc:
    static-path-pattern: /files/**
  datasource:
    first:
      url: jdbc:mysql://172.18.0.10:3306/saaes_admin?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123
      configuration:
        maximum-pool-size: 20
    second:
      url: jdbc:postgresql://localhost:5432/saaes_admin
      username: postgres
      password: 123456
      configuration:
        maximum-pool-size: 20
  data:
    redis:
      host: 172.18.0.11
      port: 6379
      database: 0
      timeout: 60000
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 20
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      password: root
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  devtools:
    livereload:
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/**/*.xml
  typeAliasesPackage: com.saaes.system.client.entity
  typeHandlersPackage: com.saaes.system.client.handler
  global-config:
    db-config:
      id-type: auto  # 主键策略

#saaes-config:
#    video-post-url: http://10.100.147.76:5000/process_video
#    base-url: http://10.200.70.15:9002
