version: '1.0'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app-net:
        ipv4_address: 172.18.0.10

  redis:
    image: redis:3.0
    container_name: redis3
    restart: always
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      app-net:
        ipv4_address: 172.18.0.11

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lxzj_backend
    restart: always
    ports:
      - "9002:9002"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./backend/resources:/app/resources
    networks:
      app-net:
        ipv4_address: 172.18.0.12

volumes:
  mysql_data:
  redis_data:

networks:
  app-net:
    name: app_bridge_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
